title: ZUKMA
tagline: Decentralized X11-based cryptocurrency
description: Decentralized blockchain
baseurl: "https://zukma.org"
url: "/docs"

markdown: kramdown
sass:
  sass_dir: assets/sass

collections:
  - panels

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-remote-theme

jekyll-mentions:
    base_url: https://github.com

exclude: [
   "Gemfile",
   "Gemfile.lock",
   "node_modules",
   "cibuild",
   "gulpfile.js",
   "package.json",
   "_site",
   "src",
   "vendor",
   "CNAME",
   "LICENSE.md",
   "maintenance.md",
   "Rakefile"
 ]
remote_theme: pages-themes/midnight@v0.2.0
